DO $$
BEGIN
  ALTER TABLE "Vessel" RENAME COLUMN "width" TO "beam";
  ALTER TABLE "Vessel" DROP COLUMN "description";
  ALTER TABLE "Vessel" DROP COLUMN "deadWeight";
  ALTER TABLE "Vessel" DROP COLUMN "ballastWater";
  ALTER TABLE "Vessel" ALTER COLUMN "length" DROP NOT NULL;
  ALTER TABLE "Vessel" ALTER COLUMN "beam" DROP NOT NULL;
  ALTER TABLE "Vessel" ADD COLUMN "flag" VARCHAR(255) NOT NULL DEFAULT 'VN';
  ALTER TABLE "Vessel" ALTER COLUMN "flag" DROP DEFAULT;
  ALTER TABLE "Vessel" ADD COLUMN "type" VARCHAR(255) NULL;
  ALTER TABLE "Vessel" ADD COLUMN "builder" VARCHAR(255) NULL;
  ALTER TABLE "Vessel" ADD COLUMN "built" VARCHAR(255) NULL;
  ALTER TABLE "Vessel" ADD COLUMN "owner" VARCHAR(255) NULL;
  ALTER TABLE "Vessel" ADD COLUMN "manager" VARCHAR(255) NULL;
  ALTER TABLE "Vessel" ADD COLUMN "maxDraught" VARCHAR(255) NULL;
  ALTER TABLE "Vessel" ADD COLUMN "class" VARCHAR(255) NULL;
  ALTER TABLE "Vessel" ADD COLUMN "nt" VARCHAR(255) NULL;
  ALTER TABLE "Vessel" ADD COLUMN "gt" VARCHAR(255) NULL;
  ALTER TABLE "Vessel" ADD COLUMN "teu" VARCHAR(255) NULL;
  ALTER TABLE "Vessel" ADD COLUMN "dwt" VARCHAR(255) NULL;
  ALTER TABLE "Vessel" ADD COLUMN "gas" VARCHAR(255) NULL;
  ALTER TABLE "Vessel" ADD COLUMN "crude" INT NULL;
  ALTER TABLE "Vessel" ADD COLUMN "longitude" FLOAT NULL;
  ALTER TABLE "Vessel" ADD COLUMN "latitude" FLOAT NULL;
  ALTER TABLE "Vessel" ADD COLUMN "heading" VARCHAR(255) NULL;
  ALTER TABLE "Vessel" ADD COLUMN "speed" DOUBLE PRECISION NULL;
  ALTER TABLE "Vessel" ADD COLUMN "callSign" VARCHAR(255) NULL;
END $$;
