services:
  smartbas_frontend_prod:
    image: bas-fe-prod
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - bas-prod
    restart: always
networks:
  bas-prod:
    driver: bridge
