services:
  bas_frontend:
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 2G
        reservations:
          cpus: "0.5"
          memory: 256M
    image: bas-fe-dev-test
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3010:3000"
    networks:
      - bas-dev
    restart: no
networks:
  bas-dev:
    driver: bridge
