services:
  smartbas_frontend_dev:
    image: smartbas-fe-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    networks:
      - smartbas-dev
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
networks:
  smartbas-dev:
    driver: bridge
