services:
  smartbas_frontend_prod:
    image: bas-fe-prod
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - bas-prod
    restart: always
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2048M
        reservations:
          cpus: '0.25'
          memory: 256M
networks:
  bas-prod:
    driver: bridge
