services:
  # Backend service
  bas_backend_prod:
    build:
      context: ./bas-api
      dockerfile: Dockerfile
    container_name: bas_backend_prod
    network_mode: host
    command:
      # Use the environment variable directly in the command
      - "/bin/bash"
      - "-c"
      - "/app/wait-for-it.sh ${KAFKA_HOST} && npm start"
    volumes:
      - ./backend/public:/app/public
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    restart: always
    env_file:
      - ./bas-api/.env

  # Frontend service
  bas_frontend_prod:
    image: bas-fe-prod
    build:
      context: ./bas-front-end
      dockerfile: Dockerfile
    ports:
      - "3040:3000"
    networks:
      - bas-prod
    restart: always

networks:
  bas-prod:
    driver: bridge
