export const CLOUD_PERMISSION = {
  BAS_RECORDING_DELETE: 'BAS_RECORDING_DELETE',
  BAS_RECORDING_VIEW: 'BAS_RECORDING_VIEW',
  BAS_RECORDING_CREATE: 'BAS_RECORDING_CREATE',
  BAS_RECORDING_EDIT: 'BAS_RECORDING_EDIT',
};
