export const OWNER_ROLE = 1;
export const REFRESH_TOKEN_KEY = 'refreshToken';
export const DEFAULT_AMOUNT = 5;
export const DEFAULT_AMOUNT_MAX = 10000;
export const DEFAULT_LIMIT = 5;
export const DEFAULT_OFFSET = 0;
export const DEFAULT_PAGE = 0;
export const IMAGE_SIZE = 1024 * 1024 * 1; // 1MB
export const IMAGE_CHARACTER_SIZE = 100; // 100 characters
export const TIME_ZONE = 'Asia/Ho_Chi_Minh'