/**
 * @file system-permission.ts
 * @module system-permission
 * @description: permission for system
 *
 * @features:
 * - PORT_DASHBOARD
 * - BERTH_DASHBOARD
 * - RECORDING_MANAGEMENT
 * - ALARM_MANAGEMENT
 * - ALARM_SETTING
 * - PORT_INFORMATION
 * - BERTH_MANAGEMENT
 * - VESSEL_MANAGEMENT
 *
 */
export const SystemPermission = {
  PORT_DASHBOARD_VIEW: 'PORT_DASHBOARD_VIEW',

  BERTH_DASHBOARD_VIEW: 'BERTH_DASHBOARD_VIEW',
  BERTH_DASHBOARD_EDIT: 'BERTH_DASHBOARD_EDIT',

  RECORDING_MANAGEMENT_VIEW: 'RECORDING_MANAGEMENT_VIEW',
  RECORDING_MANAGEMENT_EDIT: 'RECORDING_MANAGEMENT_EDIT',
  RECORDING_MANAGEMENT_SYNC: 'RECORDING_MANAGEMENT_SYNC',
  RECORDING_MANAGEMENT_EXPORT: 'RECORDING_MANAGEMENT_EXPORT',
  RECORDING_MANAGEMENT_DELETE: 'RECORDING_MANAGEMENT_DELETE',

  ALARM_MANAGEMENT_VIEW: 'ALARM_MANAGEMENT_VIEW',
  ALARM_MANAGEMENT_DELETE: 'ALARM_MANAGEMENT_DELETE',

  ALARM_SETTING_VIEW: 'ALARM_SETTING_VIEW',
  ALARM_SETTING_EDIT: 'ALARM_SETTING_EDIT',

  PORT_INFORMATION_EDIT: 'PORT_INFORMATION_EDIT',
  PORT_INFORMATION_VIEW: 'PORT_INFORMATION_VIEW',

  BERTH_MANAGEMENT_VIEW: 'BERTH_MANAGEMENT_VIEW',
  BERTH_MANAGEMENT_EDIT: 'BERTH_MANAGEMENT_EDIT',
  BERTH_MANAGEMENT_DELETE: 'BERTH_MANAGEMENT_DELETE',
  BERTH_MANAGEMENT_CREATE: 'BERTH_MANAGEMENT_CREATE',

  VESSEL_MANAGEMENT_VIEW: 'VESSEL_MANAGEMENT_VIEW',
  VESSEL_MANAGEMENT_EDIT: 'VESSEL_MANAGEMENT_EDIT',
  VESSEL_MANAGEMENT_DELETE: 'VESSEL_MANAGEMENT_DELETE',
  VESSEL_MANAGEMENT_CREATE: 'VESSEL_MANAGEMENT_CREATE',

  USER_MANAGEMENT_VIEW: 'USER_MANAGEMENT_VIEW',
  USER_MANAGEMENT_EDIT: 'USER_MANAGEMENT_EDIT',
  USER_MANAGEMENT_DELETE: 'USER_MANAGEMENT_DELETE',
  USER_MANAGEMENT_CREATE: 'USER_MANAGEMENT_CREATE',
};
